name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-it:
    runs-on: linux.2xlarge
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v2
      - name: Run Script
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install boto3==1.16.34
          echo hello!q
          python3 tools/stats/scribe.py


concurrency:
  group: lint-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
